name: Despliegue ficticio

on:
  push:
    branches:
      - main
      - '*'

jobs:
  deploy:
    runs-on: labs-runner
    steps:
      - name: Despliegue ficticio
        if: github.ref == 'refs/heads/main'
        env:
          API_KEY: ${{ secrets.PROD_API_KEY }}
        run: |
          echo "Desplegando en producción con API Key: $API_KEY"
          echo "Despliegue en producción exitoso"

      - name: Despliegue ficticio en staging
        if: github.ref != 'refs/heads/main'
        env:
          API_KEY: ${{ secrets.STAGING_API_KEY }}
        run: |
          echo "Desplegando en staging con API Key: $API_KEY"
          echo "Despliegue en staging exitoso"
