name: Despliegue por entorno

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    name: Desplegar en ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Mostrar información del entorno
        run: |
          echo "Entorno seleccionado: ${{ inputs.environment }}"
          echo "API_URL: env.API_URL"
          echo "LOG_LEVEL: env.LOG_LEVEL"
